version: '2'

services:

  software:
    build:
      context: './build/php-apache'
    container_name: 'software'
    depends_on:
      - 'database'
    networks:
      - 'frontend'
      - 'backend'
    ports:
      - '7666:80'
    restart: 'always'

  database:
    build:
      context: './build/mariadb'
    container_name: 'database'
    environment:
      TZ: 'America/Chicago'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'domainmod'
      MYSQL_USER: 'domainmod'
      MYSQL_PASSWORD: 'password'
    networks:
      - 'backend'
    ports:
      - '3306:3306'
    restart: 'always'
    volumes:
      - './database:/var/lib/mysql'

networks:
  backend:
  frontend:
